### ISSUE TITLE
SASS not compiling

### ISSUE THREAD

**Issue by sturtus** [BioPhoton/Ionic-Angular-Headless-Drupal-Demo#16]
Something is up with gulp-sass or node-sass. Upon "ionic serve", the served up Ionic site does not have an /assets/css/ionic.app.css file, and there are errors in npm-install:

> node-sass@2.1.1 install /Users/sturtr1/Developer/MRP/mrp3/app/node_modules/node-sass
> node scripts/install.js

module.js:327
    throw err;
    ^

Error: Cannot find module 'process-nextick-args'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/sturtr1/Developer/MRP/mrp3/app/node_modules/bl/node_modules/readable-stream/lib/_stream_duplex.js:21:23)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

**Comment by sturtus** [comment]
Resolved by modifying package.json with updated gulp-sass, version 2.2.0

**Comment by BioPhoton** [comment]
Fixed it in version 1.1.3.

Alos implemented server errors for register and login
